import React from 'react';
import { useState, useEffect, useRef } from 'react';
import { Mic, MicOff, Bot, User, Loader2 } from 'lucide-react';
import { cn } from '../../lib/utils'; // Note: Adjust paths as needed

// --- UI Component Imports ---
import { Button } from '../../components/ui/Button';
import { Avatar } from '../../components/ui/Avatar';

// --- Custom Hook Imports ---
// You will need to provide your own implementation of a useToast hook.
// Example: import { useToast } from '../../hooks/use-toast'; 

// --- Mock API Function (Replace with your actual fetch call) ---
/**
 * Fetches the AI vet's text and audio response from your backend.
 * @param {string} query The user's spoken query.
 * @param {string} [petName] The name of the pet, if available.
 * @returns {Promise<{responseText: string, responseAudio: string}>}
 */
const getVetResponseAPI = async (query, petName) => {
  console.log("API CALL: Sending query to backend:", { query, petName });
  // API Call: Replace this with a fetch to your Node/Express backend.
  // Example:
  // const response = await fetch('/api/vet-consult', {
  //   method: 'POST',
  //   headers: { 'Content-Type': 'application/json' },
  //   body: JSON.stringify({ query, petName })
  // });
  // if (!response.ok) throw new Error('Failed to get AI response');
  // return response.json();

  // For now, returning mock data after a delay to simulate a network request.
  return new Promise(resolve => setTimeout(() => {
    resolve({
      responseText: `Okay, regarding ${petName || 'your pet'}, you asked about "${query}". Based on that, I'd recommend checking their gums to see if they are pale. Also, monitor their appetite closely for the next 24 hours.`,
      // This would be a URL to an audio file generated by your backend
      responseAudio: "https://example.com/path/to/response.mp3" 
    });
  }, 1500));
};

// Check for browser's SpeechRecognition API support
const SpeechRecognition =
  typeof window !== 'undefined' ? (window.SpeechRecognition || window.webkitSpeechRecognition) : null;

/**
 * @typedef {object} Message
 * @property {number} id - Unique identifier for the message.
 * @property {'user' | 'ai'} sender - Who sent the message.
 * @property {string} text - The content of the message.
 */

/**
 * An AI-powered voice consultation component.
 * @param {object} props - The component props.
 * @param {string} [props.petName] - The name of the pet for context.
 */
export default function AiVetConsult({ petName }) {
  const [isListening, setIsListening] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  /** @type {[Message[], React.Dispatch<React.SetStateAction<Message[]>>]} */
  const [conversation, setConversation] = useState([]);
  const recognitionRef = useRef(null);
  const audioRef = useRef(null);
  
  // NOTE: You need to provide a `useToast` hook for this to work.
  // For now, we'll use a placeholder if it's not available.
  const toast = (...args) => console.log('Toast:', ...args); // const { toast } = useToast();

  useEffect(() => {
    if (!SpeechRecognition) {
      toast({
        title: 'Browser Not Supported',
        description: 'Speech recognition is not supported in your browser. Please try Chrome or Safari.',
        variant: 'destructive',
      });
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.continuous = false;
    recognition.interimResults = false;
    recognition.lang = 'en-US';

    recognition.onstart = () => setIsListening(true);
    recognition.onend = () => setIsListening(false);
    recognition.onerror = (event) => {
      console.error('Speech recognition error:', event.error);
      toast({
        title: "Voice Error",
        description: `An error occurred: ${event.error}. Please try again.`,
        variant: "destructive",
      });
      setIsListening(false);
    };

    recognition.onresult = (event) => {
      const transcript = event.results[0][0].transcript;
      handleUserQuery(transcript);
    };
    
    recognitionRef.current = recognition;
  }, [toast]);

  const handleUserQuery = async (query) => {
    if (!query) return;

    // Add user message to conversation
    setConversation(prev => [...prev, { id: Date.now(), sender: 'user', text: query }]);
    setIsProcessing(true);

    try {
      // API Call: Get AI response from your backend
      const result = await getVetResponseAPI(query, petName);
      const { responseText, responseAudio } = result;

      // Add AI response to conversation
      setConversation(prev => [...prev, { id: Date.now() + 1, sender: 'ai', text: responseText }]);

      // Play audio response (ensure your mock audio URL is valid for testing)
      if (audioRef.current && responseAudio) {
        audioRef.current.src = responseAudio;
        // audioRef.current.play(); // Be cautious with autoplay
      }

    } catch (error) {
      console.error("Error with AI Vet response:", error);
      toast({
        title: "AI Vet Error",
        description: "Sorry, I couldn't get a response. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsProcessing(false);
    }
  };

  const toggleListening = () => {
    if (!recognitionRef.current) {
        toast({ title: "Voice recognition not available." });
        return;
    }
    if (isListening) {
      recognitionRef.current.stop();
    } else {
      recognitionRef.current.start();
    }
  };

  return (
    <div className="p-4 rounded-lg bg-black/20 backdrop-blur-sm border border-border">
      <div className="flex flex-col h-64">
        <div className="flex-grow space-y-4 overflow-y-auto pr-2">
          {conversation.length === 0 && (
            <div className="text-center text-gray-400 flex flex-col items-center justify-center h-full">
              <Bot size={32} className="mb-2"/>
              <p>Press the microphone to start your consultation.</p>
            </div>
          )}
          {conversation.map((msg) => (
            <div key={msg.id} className={cn("flex items-start gap-3", msg.sender === 'user' ? "justify-end" : "justify-start")}>
              {msg.sender === 'ai' && <Avatar className="w-8 h-8 bg-primary text-primary-foreground flex items-center justify-center"><Bot size={20}/></Avatar>}
              <div className={cn("max-w-xs rounded-lg px-3 py-2 text-sm", msg.sender === 'user' ? "bg-primary text-primary-foreground" : "bg-card text-card-foreground")}>
                {msg.text}
              </div>
              {msg.sender === 'user' && <Avatar className="w-8 h-8 bg-accent text-accent-foreground flex items-center justify-center"><User size={20}/></Avatar>}
            </div>
          ))}
        </div>
        <div className="mt-4 flex flex-col items-center justify-center gap-3 pt-4 border-t border-border">
          <Button onClick={toggleListening} size="icon" className={cn("rounded-full h-16 w-16 transition-all duration-300", isListening ? 'bg-red-500 hover:bg-red-600' : 'bg-primary hover:bg-primary/90', isProcessing && 'animate-pulse')}>
            {isProcessing ? <Loader2 className="animate-spin" size={32} /> : (isListening ? <MicOff size={32} /> : <Mic size={32} />)}
          </Button>
          <p className="text-xs text-gray-400 h-4">
            {isProcessing ? "PawPal is thinking..." : (isListening ? 'Listening...' : `Tap to talk about ${petName || 'your pet'}`)}
          </p>
        </div>
      </div>
      <audio ref={audioRef} className="hidden" />
    </div>
  );
}