###
POST http://127.0.0.1:5000/predict-disease-with-symptoms
Content-Type: application/json

{
    "AnimalName": "Dog",
    "symptoms1": "Fever",
    "symptoms2": "Diarrhea",
    "symptoms3": "Vomiting",
    "symptoms4": "Weight loss",
    "symptoms5": "Dehydration"
}